/// <reference path="../../typings/index.d.ts"/>
/// <reference path="../objects/asset.ts"/>
/// <reference path="../objects/button.ts"/>
/// <reference path="../objects/label.ts"/>
/// <reference path="../objects/scene.ts"/>
/// <reference path="../objects/background.ts"/>
/// <reference path="../objects/vegetable.ts"/>
/// <reference path="../question_scenes/menu.ts"/>
/// <reference path="../question_scenes/results.ts"/> 
//# sourceMappingURL=_reference.js.map